### ISSUE TITLE
Missing favicon?

### ISSUE THREAD

**Issue by rbarilani** [apperclass/landing#1]

**Comment by inmarelibero** [comment]
confirm, but it should be ok, because web/favicon.ico exists and [https://github.com/apperclass/landing/blob/master/src/AppBundle/Resources/views/layout.html.twig#L10](https://github.com/apperclass/landing/blob/master/src/AppBundle/Resources/views/layout.html.twig#L10) should call it correctly.

@matteo but is the symfony project deployed?

**Comment by inmarelibero** [comment]
try putting

```
<link rel="shortcut icon" href="/favicon.ico">
```

instead of

```
<link rel="shortcut icon" href="favicon.ico">
```
